---
title: "Links"
description: |
  Some useful links for me!
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Seoncheol Park

Now I am a post-doctoral research fellow in the [Pacific Climate Impacts Consortium](https://www.pacificclimate.org/). I received my Ph.D. degree in statistics at Seoul National University, under the supervision of Prof. [Hee-Seok Oh](https://sites.google.com/site/heeseokoh). I was also a member of [Multiscale Methods in Statistics Lab](https://sites.google.com/view/snumultiscale/home).

### Journals

- [Journal of the Royal Statistical Society: Series B](http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-9868)

- [Journal of the Royal Statistical Society: Series C](http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-9876)

- [Biometrika](http://biomet.oxfordjournals.org/)

- [Journal of the American Statistical Association](http://amstat.tandfonline.com/loi/uasa20)

- [Annals of Statistics](https://projecteuclid.org/euclid.aos/)

- [Annals of Applied Statistics](https://imstat.org/journals-and-publications/annals-of-applied-statistics/)

- [Statistica Sinica](http://www3.stat.sinica.edu.tw/statistica/)

- [Bernoulli](https://projecteuclid.org/info/euclid.bj)

- [Environmetrics](http://onlinelibrary.wiley.com/journal/10.1002/%28ISSN%291099-095X)

- [Technometrics](http://amstat.tandfonline.com/toc/utch20/current)

- [Journal of Time Series Analysis](http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-9892)

- [Journal of Computational and Graphical Statistics](http://amstat.tandfonline.com/loi/jcgs)

- [The Electronic Journal of Statistics](https://projecteuclid.org/all/euclid.ejs)

- [Journal of Multivariate Statisitcs](http://www.journals.elsevier.com/journal-of-multivariate-analysis)

- [Annals of the Institute of Statistical Mathematics](http://link.springer.com/journal/10463)

- [Journal of Applied Statistics](http://www.tandfonline.com/loi/cjas20)

- [Journal of Agricultural, Biological and Environmental Statistics](https://link.springer.com/journal/13253)

- [Environmental and Ecological Statistics](https://link.springer.com/journal/10651)

- [Journal of Statistical Software](http://www.jstatsoft.org)

- [The R Journal](https://journal.r-project.org/)

- [Journal of the Korean Statistical Society](http://www.journals.elsevier.com/journal-of-the-korean-statistical-society/)

- [Statistics and Computing](http://link.springer.com/journal/11222)

- [Computational Statistics & Data Analysis](http://www.journals.elsevier.com/computational-statistics-and-data-analysis/)

- [Computational Statistics](http://link.springer.com/journal/180)

- [Stochastic Processes and their Applications](https://www.journals.elsevier.com/stochastic-processes-and-their-applications)

- [Applied and Computational Harmonic Analysis](http://www.journals.elsevier.com/applied-and-computational-harmonic-analysis/)

- [International Journal of Wavelets, Multiresolution and Information Processing](http://www.worldscientific.com/worldscinet/ijwmip)

- [Multiscale Modeling & Simulation](http://epubs.siam.org/journal/mmsubt)

- [Extremes](http://link.springer.com/journal/10687)

- [Spatial Statistics](http://www.journals.elsevier.com/spatial-statistics)

- [Stochastic Environmental Research and Risk Assessment](http://link.springer.com/journal/477)

- [International Statistical Review (Review Journal)](https://onlinelibrary.wiley.com/journal/17515823)

- [Wiley Interdisciplinary Reviews: Computational Statistics (Review Journal)](https://onlinelibrary.wiley.com/journal/19390068)

### Statisticians

- [Dongik Jang](http://dongikjang.github.io/)

- [Yaeji Lim](https://sites.google.com/site/yaejilim/)

- [Kyoungjae Lee](https://leekjstat.wordpress.com)

- [Yongchan Kwon](https://ykwon0407.github.io/)

- [Junpyo Kim](https://jpkimstat.wordpress.com)

- [Thomas Yee](https://www.stat.auckland.ac.nz/~yee/) [(Information about his papers)](https://www.stat.auckland.ac.nz/~yee/updates/)

- [Philippe Naveau](http://www.lsce.ipsl.fr/Phocea/Pisp/visu.php?id=44&uid=naveau)

- [Spatio-Temporal Statistics Research Group, KAUST](https://stsda.kaust.edu.sa/Pages/Home.aspx)

- [Environmental Statistics Research Group, KAUST](https://es.kaust.edu.sa/Pages/Home.aspx)

- [Extreme Statistics Research Group, KAUST](https://extstat.kaust.edu.sa/Pages/Home.aspx)

- [Paul Northrop](http://www.homepages.ucl.ac.uk/~ucakpjn/index.html)

- [Philip Jonathan](http://www.lancs.ac.uk/~jonathan/index.html)

- [Denis Allard](https://informatique-mia.inra.fr/biosp/homepage-denis-allard#Skew)

- [Piotr Fryzlewicz](http://stats.lse.ac.uk/fryzlewicz/)

- [Brian J. Reich](http://www4.stat.ncsu.edu/~reich/)

- [Huixia Judy Wang](https://blogs.gwu.edu/judywang/)

- [Hsin-Cheng Huang](http://sites.stat.sinica.edu.tw/hchuang/publications/)

- [Maarten Jansen](http://homepages.ulb.ac.be/~majansen/)

- [Cheolwoo Park](https://faculty.franklin.uga.edu/cpark/)

- [Stefano Castruccio](http://www.mas.ncl.ac.uk/~nsc141/)

- [Jenny Wadsworth, Lancaster University](http://www.lancaster.ac.uk/~wadswojl/)

- [Anna Kiriliouk](http://annakiriliouk.weebly.com)

- [R Project Flammability, Matthew Leonawicz](http://leonawicz.github.io/Flammability/index.html)

- [Mathieu Ribatet (Author of SpatialExtremes)](http://www.math.univ-montp2.fr/~ribatet/index.html)

- [Thordis L. Thorarinsdottir](https://www.nr.no/~thordis/index.html)

- [Stephane Girard](http://mistis.inrialpes.fr/people/girard/index.html)

- [Leo Belzile](http://sma.epfl.ch/~lbelzile/index.html)

- [Yen-Chi Chen](http://faculty.washington.edu/yenchic/)

- [Gogamza, R 기반 데이터 시각화 저자](http://freesearch.pe.kr/)

- [Ruiyan Luo](http://sites.gsu.edu/rluo/)

- [Laura Maria Sangalli](http://www1.mate.polimi.it/~sangalli/index.html)

- [Marco Di Marzio](https://www.unich.it/ugov/person/1200)

- [Marco Geraci (`lqmm` package)](https://marcogeraci.wordpress.com/software/)

### Useful Sites

- [Seeing Theory](https://seeing-theory.brown.edu)

- [IMS Bulletin Online](http://bulletin.imstat.org)

- [Statistical Methods for Atmospheric & Oceanic Sciences (STATMOS)](https://www.statmos.washington.edu/)

- [The International Environmetrics Society (TIES)](http://www.environmetrics.org)

- [The Spatial Statistics Society](http://www.spatialstatistics.info)

- [BIRS Workshop Lecture Videos](http://www.birs.ca/videos/subject/62)

- [Workshop on Dependence, Stability, and Extremes](https://homepages.uc.edu/~wangyz/misc/2016Workshop/index.html)

- [Spatial Extremes and Environmental Sustainability: Statistical Methods and Applications in Geophysics and the Environment](http://www.cces.ethz.ch/projects/hazri/EXTREMES)

- [Videos, Isaac Newton Institute for Mathematical Sciences](https://www.newton.ac.uk/science/programmes)

- [Graduate Online Course, Penn State](https://onlinecourses.science.psu.edu/statprogram/programs)

- [PhD and postdoc position offers, LU Leuven](https://lstat.kuleuven.be/jobs)

- [Kaggle](https://www.kaggle.com)

- [DACON](https://dacon.io)

- [r-spatial](http://r-spatial.org/)

- [Links of Existing Packages for use in Climate Analysis, University of Exeter](http://www1.secam.ex.ac.uk/r-packages.dhtml)

- [Extreme Value Analysis Software, The Weather and Climate Impact Assesment Science Program](http://www.assessment.ucar.edu/toolkit/)

- [R Resources for Hydrologists](http://abouthydrology.blogspot.kr/2012/08/r-resources-for-hydrologists.html)

- [Statistics of Weather and Climate Extremes](http://www.isse.ucar.edu/extremevalues/software.html)

- [서울특별시 빅데이터 캠퍼스](https://bigdata.seoul.go.kr/main.do)

- [극지원격탐사센터](http://krsc.polar.re.kr/main.html)

### Data

- [National Climatic Data Center - NOAA](http://www.ncdc.noaa.gov/)

- [Community Modeling and Analysis (CMAS) - CMAQ](https://www.cmascenter.org/cmaq/)

- [National Climate Data Service System (NCDSS, 기상청 국가기후데이터센터)](http://sts.kma.go.kr/jsp/home/contents/main/main.do)

- [PSD Web Products and Tools, NOAA](http://www.esrl.noaa.gov/psd/products/analysis/)

- [The Sounding of the Atmosphere using Broadband Emission Radiometry (SABER)](http://saber.gats-inc.com/index.php)

- [Climate Indices: Monthly Atmospheric and Ocean Time Series, NOAA](http://www.esrl.noaa.gov/psd/data/climateindices/list/)

- [GHCN Gridded Products, NOAA](http://www.ncdc.noaa.gov/temp-and-precip/ghcn-gridded-products/)

- [Goddard Earth Sciences Data and Information Services Centerm NASA](http://disc.sci.gsfc.nasa.gov)

- [NASA Exoplanet Archive](http://exoplanetarchive.ipac.caltech.edu/docs/data.html)

- [Geospatial-Data.gov](https://www.data.gov/geospatial/)

- [Pierce County Open GeoSpatial Data Portal](http://gisdata.piercecowa.opendata.arcgis.com)

- [Minnesota Geospatial Commons](https://gisdata.mn.gov/organization/us-mn-state-metrogis)

- [Meteorological Data Sources, Oscar Perpiñán Lamigueiro](https://github.com/oscarperpinan/mds/wiki)

- [Berkeley Earth](http://berkeleyearth.org/)

- [Data USA](https://datausa.io)

- [Awesome Public Datasets](https://github.com/caesar0301/awesome-public-datasets)

- [The Data and Story Library](http://lib.stat.cmu.edu/DASL/)

- [Queensland governments Wetlands Information (for maps)](http://wetlandinfo.ehp.qld.gov.au/wetlands/)

- [CrimeStat](http://www.nij.gov/topics/technology/maps/pages/crimestat.aspx)

- [National River Flow Archive (Great Britain)](https://nrfa.ceh.ac.uk/data/search)

- [CANOPEX database contains data(캐나다 수자원 자료)](http://canopex.etsmtl.net)

- [Seoul Open Data Plaza (서울 열린 데이터 광장)](http://data.seoul.go.kr/)

- [Korea Public Data Portal (공공데이터포털)](https://www.data.go.kr)

- [K-ICT 빅데이터센터](https://kbig.kr/?q=data_library/data_library_list)

- [Air Korea (에어코리아)](https://www.airkorea.or.kr/)

- [Korea Polar Data Center (한국 극지 데이터 센터)](http://kpdc.kopri.re.kr/)

- [한국도로공사 고속도로 공공데이터 포털](http://data.ex.co.kr)

- [국가공간정보포털](http://www.nsdi.go.kr/?menuno=2679)

- [보건복지데이터포털](https://data.kihasa.re.kr/index.jsp)

- [기상자료 개방포털](https://data.kma.go.kr/cmmn/main.do)

- [한강 홍수통제소](http://www.hrfco.go.kr/main.do)

- [낙동강 홍수통제소](http://www.nakdongriver.go.kr/html/hydro/realTime_2_1.jsp)

- [물환경정보시스템](http://water.nier.go.kr/publicMain/mainContent.do)

- [수질총량정보시스템](http://tmdlms.nier.go.kr/Intro.do?)


- [TLC Trip Record Data](http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml)